function info_stru = get_infoStru()
	info_stru = struct('feasibility',false, 'r', nan, ...
					'alpha', nan, 'E', nan, 'Etilde', nan, ...
                    'P', nan, 'nu', nan, 'xi', nan, ...
					'LMI', nan);
end